version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: card-adder-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - card-adder-network

volumes:
  redis_data:

networks:
  card-adder-network:
    driver: bridge 